### ISSUE TITLE
Routes Not Working When Embedded

### ISSUE THREAD

**Issue by thompson4822** [jorgegorka/svelte-router#10]
When I run my svelte-router application via `npm run dev`, everything is working just as it should - I can pull up my index page, go to a login or sign up page, etc. Unfortunately, when I build and then include everything inside my Spring Boot project as a static resource, going to any page other than '/' no longer works. Do you know what might be causing this?

**Comment by jorgegorka** [comment]
Hi @thompson4822 

Svelte Router is designed to be used in Single Page Applications. If you create static versions of each page it won't work.
