### ISSUE TITLE
Links pointing to address on same host but different port are incorrectly captured

### ISSUE THREAD

**Issue by UnwrittenFun** [jorgegorka/svelte-router#101]
I'm hosting an app (in dev) on `localhost:8080` using svelte-router-spa and I need to link to another locally hosted app at e.g. `localhost:8081`. This navigation seems to be captured by svelte-router-spa so sends up 404ing.

Changing the hostname to 127.0.0.1 for the second url works around this so my guess is something is checking hostname but not also port.

**Comment by UnwrittenFun** [comment]
Just saw there appears to be a PR to fix just this! #100

**Comment by jorgegorka** [comment]
@UnwrittenFun   The PR was merged.  Version 5.8.4 now consider different ports.
