### ISSUE TITLE
Navigate.default instead of Navigate needed

### ISSUE THREAD

**Issue by freeman-g** [jorgegorka/svelte-router#105]
Hi, I noticed with the following versions of dependencies that I need to use

```
<Navigate.default to="/">Home</Navigate.default>
```
instead of
```
<Navigate to="/">Home</Navigate>
```

This looks like a similar problem to the issue with using <Router.default>, which I noticed I no longer need to do with these dependencies.

current dependencies:

```
├─┬ @rollup/plugin-commonjs@17.1.0
│ ├─┬ @rollup/pluginutils@3.1.0
│ │ ├── @types/estree@0.0.39
│ │ ├── estree-walker@1.0.1
│ │ └── picomatch@2.2.2
│ ├── commondir@1.0.1
│ ├── estree-walker@2.0.2
│ ├─┬ glob@7.1.6
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ ├── once@1.4.0 deduped
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.4
│ │ ├─┬ minimatch@3.0.4
│ │ │ └─┬ brace-expansion@1.1.11
│ │ │   ├── balanced-match@1.0.0
│ │ │   └── concat-map@0.0.1
│ │ ├─┬ once@1.4.0
│ │ │ └── wrappy@1.0.2 deduped
│ │ └── path-is-absolute@1.0.1
│ ├─┬ is-reference@1.2.1
│ │ └── @types/estree@0.0.39 deduped
│ ├─┬ magic-string@0.25.7
│ │ └── sourcemap-codec@1.4.8
│ └─┬ resolve@1.20.0
│   ├─┬ is-core-module@2.2.0
│   │ └─┬ has@1.0.3
│   │   └── function-bind@1.1.1
│   └── path-parse@1.0.6
├─┬ @rollup/plugin-node-resolve@11.2.0
│ ├── @rollup/pluginutils@3.1.0 deduped
│ ├─┬ @types/resolve@1.17.1
│ │ └── @types/node@14.14.27
│ ├── builtin-modules@3.2.0
│ ├── deepmerge@4.2.2
│ ├── is-module@1.0.0
│ └── resolve@1.20.0 deduped
├─┬ rollup@2.39.0
│ └── fsevents@2.3.2
├─┬ rollup-plugin-css-only@3.1.0
│ └─┬ @rollup/pluginutils@4.1.0
│   ├── estree-walker@2.0.2 deduped
│   └── picomatch@2.2.2 deduped
├─┬ rollup-plugin-livereload@2.0.0
│ └─┬ livereload@0.9.1
│   ├─┬ chokidar@3.5.1
│   │ ├─┬ anymatch@3.1.1
│   │ │ ├── normalize-path@3.0.0 deduped
│   │ │ └── picomatch@2.2.2 deduped
│   │ ├─┬ braces@3.0.2
│   │ │ └─┬ fill-range@7.0.1
│   │ │   └─┬ to-regex-range@5.0.1
│   │ │     └── is-number@7.0.0
│   │ ├── fsevents@2.3.2 deduped
│   │ ├─┬ glob-parent@5.1.1
│   │ │ └── is-glob@4.0.1 deduped
│   │ ├─┬ is-binary-path@2.1.0
│   │ │ └── binary-extensions@2.2.0
│   │ ├─┬ is-glob@4.0.1
│   │ │ └── is-extglob@2.1.1
│   │ ├── normalize-path@3.0.0
│   │ └─┬ readdirp@3.5.0
│   │   └── picomatch@2.2.2 deduped
│   ├── livereload-js@3.3.1
│   ├── opts@2.0.2
│   └─┬ ws@6.2.1
│     └── async-limiter@1.0.1
├─┬ rollup-plugin-svelte@7.1.0
│ ├── require-relative@0.8.7
│ └─┬ rollup-pluginutils@2.8.2
│   └── estree-walker@0.6.1
├─┬ rollup-plugin-terser@7.0.2
│ ├─┬ @babel/code-frame@7.12.13
│ │ └─┬ @babel/highlight@7.12.13
│ │   ├── @babel/helper-validator-identifier@7.12.11
│ │   ├─┬ chalk@2.4.2
│ │   │ ├─┬ ansi-styles@3.2.1
│ │   │ │ └─┬ color-convert@1.9.3
│ │   │ │   └── color-name@1.1.3
│ │   │ ├── escape-string-regexp@1.0.5
│ │   │ └─┬ supports-color@5.5.0
│ │   │   └── has-flag@3.0.0
│ │   └── js-tokens@4.0.0
│ ├─┬ jest-worker@26.6.2
│ │ ├── @types/node@14.14.27 deduped
│ │ ├── merge-stream@2.0.0
│ │ └─┬ supports-color@7.2.0
│ │   └── has-flag@4.0.0
│ ├─┬ serialize-javascript@4.0.0
│ │ └─┬ randombytes@2.1.0
│ │   └── safe-buffer@5.2.1
│ └─┬ terser@5.6.0
│   ├── commander@2.20.3
│   ├── source-map@0.7.3
│   └─┬ source-map-support@0.5.19
│     ├── buffer-from@1.1.1
│     └── source-map@0.6.1
├─┬ sirv-cli@1.0.11
│ ├── console-clear@1.1.1
│ ├── get-port@3.2.0
│ ├── kleur@3.0.3
│ ├── local-access@1.1.0
│ ├─┬ sade@1.7.4
│ │ └── mri@1.1.6
│ ├── semiver@1.1.0
│ ├─┬ sirv@1.0.11
│ │ ├── @polka/url@1.0.0-next.11
│ │ ├── mime@2.5.0
│ │ └── totalist@1.1.0
│ └── tinydate@1.3.0
├── svelte@3.32.3
└─┬ svelte-router-spa@5.8.4
  └── url-params-parser@1.0.3
```

**Comment by moalamri** [comment]
Big thank to this package creator for the awesome SPA router also big thank to @si3nloong for refactoring the script from CommonJS to ES Module.
You can avoid all of these `import` issues using @si3nloong [fork](https://github.com/si3nloong/svelte-router/)

**Comment by si3nloong** [comment]
@moalamri great. At current moment, anyone have issue when using `svelte-router-spa` with `snowpack` or `vite` (they are expecting esm). Can just change your `package.json` as below

`  
"dependencies": {
    "svelte-router-spa": "https://github.com/si3nloong/svelte-router"
}
`
not sure is @jorgegorka willing to accept our pr? 🤔

**Comment by moalamri** [comment]
@si3nloong that's exactly what I did and it's working great with `vite`
Although I have noticed some strange behavior with `navigateTo` function as some times it doesn't navigate, I should wait for others to test it as well (it could be from my side)...
Anyways thank you for taking the time to refractor this. I hope @jorgegorka will accept the PR

**Comment by moalamri** [comment]
I have run some tests and it seems like `navigateTo` is not functional if it's the first initialize of the page (when I open page in new tab or refresh the current page). If I navigate to that page again and call `navigateTo`, it will work fine. I have tested it with `updateBrowserHistory` set to `true` and `false`, but still the same. I don't know if it's a bug in the original package because I couldn't use it with CJS.

**Comment by jorgegorka** [comment]
Hi all:

Version 6 has been released and it has support for esm packages.

**Comment by moalamri** [comment]
@si3nloong the issue I mentioned is not related to your refactoring nor to the package it self. It is because I was calling `navigateTo ` to a route that being guarded with a `Promise `function so it fires along with routing action to guarded route. I made the guard async and it's working great now ..

**Comment by moalamri** [comment]
@si3nloong @jorgegorka Thank you so much guys
