### ISSUE TITLE
Router does not work properly with Vite development mode

### ISSUE THREAD

**Issue by themichaelkarpen** [jorgegorka/svelte-router#119]
I wanted to try Svelte + Vite and take advantage of hmr. However, I found some issues with this router when working in dev mode. Fortunately, the app works great with a production build.

I initialized the project using
```bash
npm init @vitejs/app
```
And chose the `Svelte` template project.

When running Vite dev mode, `npm run dev`, I found these issues:
- Browser history back button does not work, the previous route layout and component is not loaded.
- `navigateTo` is not working properly, I'm testing it with prefixed routes. The route ends up resolving to the 404 page.

Additionally, I noticed a couple other things:
- VSCode also complains (but does not error) in App.Svelte using `prefix`. Perhaps this is the reason `navigateTo` does not work properly.
```svelte
<Router {routes} options={{ prefix: 'test' }} />
```
- Initial page load for the app takes about a second longer then a regular Svelte (rollup) app.

After building and testing in production, it works fine.   

__Any thoughts on getting the above items working with Vite dev?__

**Comment by lobiklukas** [comment]
Same for me. I am using Router without prefix. When I debugged the package code I notice this.

When the application is loaded userDefinedRoutes are successfully stored.
![image](https://user-images.githubusercontent.com/45765609/121602218-455acf00-ca47-11eb-89e1-9cc42b7f8f8e.png)

After using `navigateTo("admin")` userDefinedRoutes are empty.
![image](https://user-images.githubusercontent.com/45765609/121603208-b51d8980-ca48-11eb-8a46-aef9c7b0796a.png)

**Comment by Saipov** [comment]
Try adding the router to the exceptions in the vite.config.js
export default defineConfig({
  plugins: [svelte()],
  optimizeDeps: { exclude: ["svelte-router-spa"] }
})

**Comment by lobiklukas** [comment]
> Try adding the router to the exceptions in the vite.config.js
> 
> export default defineConfig({
> 
>   plugins: [svelte()],
> 
>   optimizeDeps: { exclude: ["svelte-router-spa"] }
> 
> })

Thanks, routing is now working properly.
