### ISSUE TITLE
Error in readme.md

### ISSUE THREAD

**Issue by artecoop** [jorgegorka/svelte-router#12]
Hey @jorgegorka 
I found a typo in your example: 
```
SpaRouter(
  routes,
  pathName: document.location.href
).currentRoute
```
named parameters in javascript aren't permitted.

Also, provide a breaking changes md or highlight them in the readme. A simple "check the docs" it's just confusing.

**Comment by jorgegorka** [comment]
Hi @artecoop 

Thanks for noticing the typo. I've fixed it.

I'll try and explain things better in future releases. I know documentation is very important and I do my best to make it easy to read and understand. Apologies if something is not as clear as it should be.
