### ISSUE TITLE
Route with named param is not working

### ISSUE THREAD

**Issue by allochi** [jorgegorka/svelte-router#123]
Hi, I really like the direction of this router, and I would love to use it in my current project. so far all is well, until I added a named param route. I tried to debug what's the problem, but I can't figure it out so far.

Basically I have routes like this

-- routes.js
```js
import Home from "./views/Home.svelte";
import About from "./views/About.svelte";
import Greet from "./views/Greet.svelte";
import Layout from "./views/Layout.svelte";

const routes = [
	{ name: "/", component: Home, layout: Layout },
	{ name: "/about", component: About, layout: Layout },
	{ name: "/greet/:name", component: Greet, layout: Layout },
];

export { routes };
```

-- App.svelte
```svelte
<script>
  import { Router } from "svelte-router-spa";
  import { routes } from "./routes";
</script>

<Router {routes} />
```

-- NavigationLinks.svelte
```svelte
<ul>
  <li><a href="/">Home</a></li>
  <li><a href="/about">About</a></li>
  <li><a href="/greet/world">Greet world</a></li>
  <li><a href="/greet/svelte">Greet svelte</a></li>
</ul>
```

-- Layout.svelte
```svelte
<script>
	import { Route } from "svelte-router-spa";
	import NavigationLinks from "../components/NavigationLinks.svelte";

	export let currentRoute;
	const params = {};
</script>

<div class="app">
	<NavigationLinks />
	<section class="section">
		<Route {currentRoute} {params} />
	</section>
</div>
```

-- Greet.svelte
```svelte
<script>
	export let currentRoute;
	let { name } = currentRoute.namedParams;
</script>

<div>
	<h1>Hello {name}!</h1>
</div>
```

All the routes are working fine, except when I alternate between `/greet/world` and `/greet/svelte`, the component doesn't reload, and nothing happens. could you please elaborate/advice?

Sorry for the long post, I'm getting desperate and it would be pity to switch to another router. thanks in advance.

**Comment by jorgegorka** [comment]
Hello @allochi 

When you use a named param then the same component is being rendered `Greet.svelte` in your example.   Svelte won't rerender the component if nothing has changed so you need to have some reactive code that updates the component.

Check this example:  

https://github.com/jorgegorka/demanda/blob/master/frontend/src/views/protected/admin/layout/main_menu/item.svelte#L9-L13

Without the reactive code isActive won't be updated.
