### ISSUE TITLE
navigateTo always return 404

### ISSUE THREAD

**Issue by Mrdaviid-stack** [jorgegorka/svelte-router#129]
my code:

![image](https://user-images.githubusercontent.com/83437794/154907489-726cb045-77da-46d4-a995-dd1775407497.png)

**Comment by jorgegorka** [comment]
Hello @Mrdaviid-stack 

You are using `navigateTo` before defining the routes so it won't know about them.  

Move all routes related code to components inside `<Router {routes}>`.
