### ISSUE TITLE
how do i get query string inside a component?

### ISSUE THREAD

**Issue by chovy** [jorgegorka/svelte-router#14]
I'm passing /`login?ref=<original-route>` if they arent' logged in. In my Login component I need to redirect them to params.ref. how do I get that info?

**Comment by jorgegorka** [comment]
Using  the _currentRoute_  property.  The `<Route />` component sends a _currentRoute_ property to all its child components.

Inside your login component add `export let currentRoute` and then you will have all query params in `currentRoute.queryParams` 

 In your example it would be `currentRoute.queryParams['ref']`

**Comment by chovy** [comment]
do I import "'currentRoute" from the module or something?

**Comment by chovy** [comment]
I got it working.

**Comment by chovy** [comment]
This doesn't work. when i try to accesss /connections I should get redirected to /login?ref=/connections but instead I get 404.html

**Comment by jorgegorka** [comment]
Hi @chovy :

You are right this is a bug.  I'm working on the fix.

**Comment by jorgegorka** [comment]
I've released version 5.1.1 that should fix this error.

**Comment by chovy** [comment]
now the active class is always there.

**Comment by chovy** [comment]
i commented on the wrong ticket. this one works now.
