### ISSUE TITLE
Not able to use in webpack project

### ISSUE THREAD

**Issue by knipferrc** [jorgegorka/svelte-router#15]
Trying to use this in a webpack project but getting errors when importing as follows:

`svelte_router_spa__WEBPACK_IMPORTED_MODULE_2__.Router is not a constructor`

Any ideas?

**Comment by jorgegorka** [comment]
Hi @knipferrc 

I use rollup not webpack.

Maybe this could help?   

https://stackoverflow.com/questions/50435253/webpack-imported-module-is-not-a-constructor

**Comment by glebmolchanov** [comment]
I found solution``

**Comment by glebmolchanov** [comment]
I found solution. You should create file with this code. And import from this file. I believe this would be helpfull for webpack users.
```
const Router = require('svelte-router-spa').Router.default;
const Route = require('svelte-router-spa').Route.default;
const Navigate = require('svelte-router-spa').Navigate.default;

export {Navigate, Route, Router}
```

**Comment by MvnTruong** [comment]
> I've found solution. You should create file with this code. And import from this file. I believe this would be helpfull for webpack users.
> 
> ```
> const Router = require('svelte-router-spa').Router.default;
> const Route = require('svelte-router-spa').Route.default;
> const Navigate = require('svelte-router-spa').Navigate.default;
> 
> export {Navigate, Route, Router}
> ```

That worked perfectly, thank you @klavobit!
