### ISSUE TITLE
Component not re-rendering when id-based route changes

### ISSUE THREAD

**Issue by freyley** [jorgegorka/svelte-router#21]
In `routes.js`, I have something like:

    { name: 'show-book/:id', component: ShowBook}

And in the top of `ShowBook.svelte`:

     export let currentRoute;
     let id = currentRoute.namedParams.id;
     console.log("got the id", id, currentRoute);

But within the ShowBook component, there's a line for a different book:

          <Navigate to="/show-book/{book.id}">{book.name}</Navigate>

Clicking on that navigate link changes the URL, but does not cause the console log to happen. Suggestions?

**Comment by jorgegorka** [comment]
Hi @freyley 

Can you try this?

`$: console.log("got the id", id, currentRoute);`

**Comment by freyley** [comment]
@jorgegorka that gets me a console log with every route change, but I'm switching back and forth between id `44bdb251-bd6b-456c-8a6e-9e1a5a00425b` and id `232c3d78-ed86-4f86-8df8-fd341a4b2fd9` and it's always printing out:

got the id 232c3d78-ed86-4f86-8df8-fd341a4b2fd9

**Comment by nahuelmorata** [comment]
I have the same issue the app render /alumno/:id but when i try to navigate to /alumnos dont render but the url change

**Comment by jorgegorka** [comment]
Hi @nahuelmorata Is there any error in the console?

**Comment by nahuelmorata** [comment]
No, but the links stops working when i render the route with id based

**Comment by nahuelmorata** [comment]
I delete my code without noticing and when i recode all my project and the router work when navigate from /alumno/:id to /alumnos. I have a doubt in my old code if i put http://localhost:5000/alumnos this render the route and now with my new code respond 404, could this generate the problem?

**Comment by koglerjs** [comment]
I have a similar problem with pagination, a route that looks like name: 'p/:id'

The navigation takes effect but as the 'active route' hasn't changed (I theorize) the component does not reload and the page stays the same.
