### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by zemigpt** [jorgegorka/svelte-router#22]
I'm having a bit of trouble with nested routes.

I have the following routes.js:
```javascript
const routes = [
    {
      name: '/',
      component: ListaObras,
      layout: DefaultLayout
    },
    {
      name: 'obra/:codigo',
      component: Obra,    
      layout: DefaultLayout,
      nestedRoutes: [
        {
          name: 'auto-cliente/:numero',
          component: AutoCliente,    
        },
      ]
    },
    
    {
      name: 'subempreiteiro/:nipc',
      component: Subempreiteiro,    
      layout: DefaultLayout  
    }
  ]
```

I was expecting that the URL ``/obra/144/autocliente/3`` would be handled by AutoCliente component, but it never leaves Obra.

What am I missing?

**Comment by alois-wever** [comment]
@zemigpt I know it's a little bit late, but I run into a similar problem today. I forgot to add 

`<script>
   import { Route } from 'svelte-router-spa';
   export let currentRoute
</script>
<Route {currentRoute} />
`
to the parent Component. So perhaps you forgot to add it in your `Obra` file, too?
