### ISSUE TITLE
Electron and file:// support

### ISSUE THREAD

**Issue by nye** [jorgegorka/svelte-router#23]
Hello,

I'm trying to use it in an Electron project but when running the electron app all I get is a blank page.

Maybe it's probably because electron uses the `file://` protocol?

It's possible to add support for Electron and file://?

**Comment by jorgegorka** [comment]
Hi @nye 

Svelte-Router needs Svelte JS in order to work.  I'm not sure if you can run an Svelte JS app inside Electron. If that is the case I reckon Electron would have to run it inside a browser component so there is no file:// protocol but http://

**Comment by nye** [comment]
Hi,

Yes, of course I'm using svelte and it's completely possible to use svelte with electron. 
Also, a browser component can use a file:// protocol...

I think the problem here is that the router needs to be able to handle the file:// protocol.

Maybe if we can just choose to use a hash-based routing, there will be no problem with the protocol and so it will be possible to use it on Electron... is that possible?
