### ISSUE TITLE
It doesn't seems to work with webpack

### ISSUE THREAD

**Issue by vis97c** [jorgegorka/svelte-router#24]
I was testing a build using your plugin with webpack and rollup. The rollup bundle works like a charm but in webpack i'm getting this:

![error 1](https://user-images.githubusercontent.com/45251845/69688964-8f62a680-1095-11ea-948b-028dc03efd33.png)

If i omit the "node_modules" exclude the bundle finishes correctly.But this shows up in the browser console:

![browser](https://user-images.githubusercontent.com/45251845/69689383-cab1a500-1096-11ea-827d-9272ec67b895.png)

Can you help me with this?

this is my webpack config:

> const MiniCssExtractPlugin = require('mini-css-extract-plugin');
> const CopyPlugin = require('copy-webpack-plugin');
> const path = require('path');
> const HtmlWebpackPlugin = require('html-webpack-plugin');
> const HtmlBeautifyPlugin = require('html-beautify-webpack-plugin');
> require('es6-promise').polyfill();
> const mode = process.env.NODE_ENV || 'development';
> const isProduction = mode === 'production';
> //webpack defaults
> module.exports = {
> 	entry: {
> 		main: './src/js/app.js'
> 	},
> 	resolve: {
> 		alias: {
> 			svelte: path.resolve('node_modules', 'svelte'),
> 			'_src': path.resolve(__dirname, 'src'),
> 			'_components': path.resolve(__dirname, 'src/js/components'),
> 			'_helpers': path.resolve(__dirname, 'src/js/helpers'),
> 			'_assets': path.resolve(__dirname, 'src/assets'),
> 		},
> 		extensions: ['.mjs', '.js', '.svelte'],
> 		mainFields: ['svelte', 'browser', 'module', 'main']
> 	},
> 	output: {
> 		path: __dirname + '/public_html',
> 		filename: 'js/[name].js',
> 		chunkFilename: 'js/[name].[id].js',
>     },
>     plugins: [
>         new CopyPlugin([
>             { from: 'src/to_public', to: '', dot: true },
>             { from: 'src/dev_only', to: '', dot: true },
>         ]),
>         new HtmlWebpackPlugin({
>             filename: 'index.template',
>             template: 'src/index.template.html',
>             hash: true,
>         }),
>     ],
>     devServer: {
>         port: 3000,
>         hot: false,
>         inline: true,
>         contentBase: 'public_html',
>         proxy: {
>             '*': {
>                 target: 'http://sveldost.test/',
>                 secure: false,
>                 changeOrigin: true
>             }
>         },
>         historyApiFallback: true,
>         open: true,
>     },
> 	module: {
> 		rules: [
> 			{
> 				test: /\.js$/,
> 				exclude: /node_modules/,
> 				use: {
> 					loader: 'babel-loader'
> 				}
> 			},
> 			{
> 				test: /\.svelte$/,
> 				use: {
> 					loader: 'svelte-loader',
> 					options: {
> 						preprocess: require('svelte-preprocess')({
> 							scss: true
> 						})
> 					}
> 				}
> 			},
> 			{
> 				test: /\.css$/i,
> 				use: [
> 					isProduction ? MiniCssExtractPlugin.loader : 'style-loader',
> 					'css-loader' + (!isProduction ? '?sourceMap' : ''),
> 				]
> 			},
> 			{
> 				test: /\.s[ac]ss$/i,
> 				use: [
> 					isProduction ? MiniCssExtractPlugin.loader : 'style-loader',
> 					'css-loader' + (!isProduction ? '?sourceMap' : ''),
> 					'sass-loader' + (!isProduction ? '?sourceMap' : ''),
> 				],
> 			}
> 		]
> 	},
> 	mode,
> 	devtool: isProduction ? false : 'source-map',
> };

Thanks in advantage.

**Comment by cesc1989** [comment]
Hi @jorgegorka I got the very same error today:

```
ERROR in ./node_modules/svelte-router-spa/src/components/route.svelte 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <script>
|   export let currentRoute = {}
|   export let params = {}
 @ ./node_modules/svelte-router-spa/src/index.js 2:14-50
 @ ./src/App.svelte
 @ ./src/main.js
 @ multi ./src/main.js
```

In this other issue #15  you mentioned you use Rollup and not Webpack so it seems the project only supports Rollup no Webpack (and there's no plan to support it). Is that right?

I ask because I'm working in a project using Svelte and haven't found a decent router (this one looks very promising) but if this router doesn't work with Webpack I'm afraid I'd have to move to another JS framework.

**Comment by httpsOmkar** [comment]
I have added functionality in this pull request #58
This you can use  `svelte-router-spa-webpack`
