### ISSUE TITLE
Issues with named params in nested routes

### ISSUE THREAD

**Issue by solnsumei** [jorgegorka/svelte-router#27]
Scenerio A
```
routes = [
  {name: 'companies', component: CompaniesPage,
    nestedRoutes: [
      {name: ':id', component: CompanyPage},
    ],
 },
]
```

if I visit `/companies/{id}` route,  I am redirected to 404.html page.
Is this a bug or how `svelte-router` works? I would love to be able to write my routes like the above.

Scenerio B
```
routes = [
  {name: 'companies/:id', component: CompaniesPage,
    nestedRoutes: [
      {name: 'index', component: CompanyPage},
    ],
 },
]
```

if I visit `/companies` or `/companies/{id}` route, CompaniesPage is rendered in both. Looks like the CompanyPage is not being rendered for the `/companies/{id}` route. Is there a way to get them to render different components? Thanks.

**Comment by jorgegorka** [comment]
Hello @solnsumei 

About Scenario A  a named param is just additional information that you send to a route so it does not make sense as a single route like _{name: ':id', component: CompanyPage},_ it should be _{name: '/company/:id', component: CompanyPage},_

About Scenario B what I would do is having a route for companies and another for a single company like this:

```:javascript
routes = [
  {name: 'companies', component: CompaniesPage },
 {name: 'company/:id', component: CompanyPage }
]
```

**Comment by solnsumei** [comment]
@jorgegorka Thanks for your swift response. Your above proposal adds 3 routes instead of 2, the third one being a redundant `/company` route without the `:id` which may not be necessary. If there is a way the nested index and the core route itself can use different components, it will be a plus. Well, I figured out a way to use different components by doing this:

```
routes = [
  {name: 'companies', component: 'CompaniesPage',
  {name: 'companies/:id', component: '',
    nestedRoutes: [
      {name: 'index', component: CompanyPage},
    ],
 },
]
```

This way the `companies` route uses a different component from the `companies/:id` route.

**Comment by jorgegorka** [comment]
@solnsumei You don't need the extra _'index'_ route it's implicit in _{ name: 'company/:id', component: CompanyPage }_

That route will work for both `/company/` and `/company/some-name`
