### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by Ceyar** [jorgegorka/svelte-router#28]
Is there a way to internationalise a project with svelte-router? If yes, how would this be possible to make it using the Rich Harris advice [link](https://github.com/sveltejs/svelte/issues/1034#issuecomment-353405927)?

Thanks a lot
Best regards

Dan

**Comment by jorgegorka** [comment]
I'm currently working on adding support for internationalisation of routes. I'll have it ready in a few days.

**Comment by Ceyar** [comment]
Ok, great news!! Let me know when you have something to test.

Best regards
Dan

**Comment by jorgegorka** [comment]
Hi @Ceyar I've published version 5.2.0 with localisation support.

**Comment by Ceyar** [comment]
Hello @jorgegorka, thank you!! 
I'll test that and give you a feedback as soon as possible.

By the way, thank you for this plugin.
Have a nice day
