### ISSUE TITLE
only the root page is matched

### ISSUE THREAD

**Issue by ghmhd** [jorgegorka/svelte-router#29]
i'm new to svelte and i tried svelte-router-spa but the code i wrote doesn't seem to work
the router matches only the root page it doesn't match the login route when i navigate to /login
the code is bellow 
routes.js
`const routes = [
  {
    name: "/",
    component: Home,
    layout: PublicLayout
  },
  { name: "login", component: Login, layout: PublicLayout }
];`
PublicLayout.svelte
`<script>
  import { Route } from "svelte-router-spa";
  import NavBar from "./Nav.svelte";
  export let currentRoute;
  export let params;
</script>

<NavBar {currentRoute} />
<Route {currentRoute} {params} />
`

App.svelte

`<script>
  import { Router } from "svelte-router-spa";
  import { routes } from "./routes";
</script>

<Router {routes} />
`

**Comment by jorgegorka** [comment]
Hello @ghmhd 

Please ensure that your local server is configured in SPA mode. In a standard configuration you just need to add _-s_ to _sirv public_ inside your `package.json`

Check this note:  https://github.com/jorgegorka/svelte-router/blob/master/README.md#usage

**Comment by ghmhd** [comment]
sorry the solution was in front of my eyes and i didn't see it thank you @jorgegorka
