### ISSUE TITLE
Passing down props from main.js/App.svelte

### ISSUE THREAD

**Issue by NorseGaud** [jorgegorka/svelte-router#3]
Hello! Love the router, thank you very much for the time spent on it. Apologies, as I'm fairly new to svelte and even JS.

I have the following main.js:
```
import App from './App.svelte'
import { SpaRouter } from 'svelte-router-spa'
import { routes } from './routes'
import NotFound from './views/not_found.svelte'

SpaRouter({
  routes,
  pathName: document.location.href,
  notFound: NotFound
}).getActiveRoute

const app = new App({
	target: document.body,
	props: {
		name: 'world'
	}
});
export default app;
```

And, the following App.svelte:
```
<script>
  import { Router } from 'svelte-router-spa'

  import ApolloClient from 'apollo-boost' 
  import { setClient } from 'svelte-apollo'
  const client = new ApolloClient({ uri: 'http://localhost:4000/graphql' })
  setClient(client)
  
  export let name;
  console.log("APP: " + name);
</script>

<Router />
```

The console shows `APP: world` just fine.
However, I can't seem to get name in layout.svelte, or any of the other routed to files.

Is there a special way I need to pass the name prop through?

**Comment by jorgegorka** [comment]
Hello @NorseGaud :

The router does not send any prop to the child components. 

If you want to send information to the child component you should use Svelte's [setContext](https://svelte.dev/docs#setContext)

If you need a reactive prop or make the content available globally to any component under _Router_ then use a [store ](https://svelte.dev/docs#svelte_store) instead.

Remember that the _Route_ component sends a prop called [currentRoute](https://github.com/jorgegorka/svelte-router#currentroute) to all the components it renders so all params both _named_ and _query_ params are already available in any component by default.

**Comment by NorseGaud** [comment]
Hey @jorgegorka, thanks! I ended up using stores and they work great. 

Thanks for the info!
