### ISSUE TITLE
Improvement: onlyIf with origin url

### ISSUE THREAD

**Issue by artecoop** [jorgegorka/svelte-router#32]
Hola Hombre!
as an improvement of this good piece of code, I suggest to enable a flag into the `onlyIf` property that includes the original relative url. So we can handle it into redirect as param.

I know I can hardcode the url into the `redirect`property, but it'll be tedious and error prone.

Please consider it for one of your future releases

**Comment by jorgegorka** [comment]
Ciao @artecoop:  

Let's see if I understand your request with an example:

```
name: 'admin',
    component: AdminLayout,
    onlyIf: { guard: userIsAdmin, redirect: '/login' },
```

If I visit /admin and I'm not logged in I'm redirected to /login.  What you want is a way to redirect the user back to admin after the login is successfull ?

**Comment by artecoop** [comment]
Let's imagine having this situation:
```
name: 'admin',
component: AdminLayout,
onlyIf: { guard: userIsAdmin, redirect: '/login', includeOrigin: true },
```
I've added a new property: `includeOrigin` that if true adds to the redirect a query param with the relative url of the origin of the "guarded" request.
So, with the property set, I'll be redirect to the login url I.E.: 
`http://localhost:5000/login?returnurl=%2Fadmin`

This would be useful to keep track of entry point for guarded request, and for complex routes with multiple nested routes.

**Comment by jorgegorka** [comment]
I prefer not to add a param in the url as that may lead to security issues but we can definitely redirect to origin when a param like _includeOrigin_ is true.

another option to avoid adding a new property is having a constant called _Back_  so you can write  
`onlyIf: { guard: userIsAdmin, redirect: Back }`

**Comment by artecoop** [comment]
> I prefer not to add a param in the url as that may lead to security issues but we can definitely redirect to origin when a param like _includeOrigin_ is true.

I understand and agree

> another option to avoid adding a new property is having a constant called _Back_ so you can write
> `onlyIf: { guard: userIsAdmin, redirect: Back }`

This is brilliant!
Take your time, this isn't a primary feature for a router. Keep up with your schedule
