### ISSUE TITLE
going back in the history is not working?

### ISSUE THREAD

**Issue by DarkEye123** [jorgegorka/svelte-router#34]
I have a problem with history management.

Example:
Root of the app is running here
`http://localhost:5000`

Now I will manually enter the URL e.g. like this 
`http://localhost:5000/projects/1`

All is rendered etc. but going back button is not working

here is an example of such route
```
const routes = [
  {
    name: '/',
    component: Projects,
    layout: AppLayout,
  },
  {
    name: 'projects',
    component: Projects,
    layout: AppLayout,
  },
  {
    name: 'projects/:id',
    component: Project,
  },
];
```

I'm not sure if it is a bug or just a lack of my knowledge, but I was not able to find info about it in the readme.

**Comment by henrisokka** [comment]
I'm facing similiar issues. Back button not working on some occasions.

**Comment by mtrojahn** [comment]
Hello. If I may add to this, in a route with nested routes structured like this:
`  {
    name: 'register',
    component: RegisterLayout,
    nestedRoutes: [
      { name: 'index', component: RegisterWizard },
      { name: "step-01", component: Step01 },
      { name: "step-02", component: Step02 },
      { name: "step-03", component: Step03 },
      { name: "step-04", component: Step04 },
      { name: "step-05", component: Step05 },
      { name: "step-06", component: Step06 },
      { name: "step-07", component: Step07 }
    ],
`
It is only possible to go back 1 step. After that the browser back button gets inactivated.
