### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by acaxon** [jorgegorka/svelte-router#35]
First of all, thanks for sharing this piece of code. It's helping me a lot.

In my project I created a Breadcrumbs.svelte component that must show the current route like...  breadcrumbs. My first idea was subscribing to some Store where the active route is kept, and  I saw in your code that you use such a Store - activeRoute, but you don't export it. 

Could you give me some light in this question?

Thanks in advance for your attention.

**Comment by jorgegorka** [comment]
Hello: @acaxon Glad you like it. Thank you.

You have all the information about the active route in a property called  currentRoute.  

https://github.com/jorgegorka/svelte-router#layouts-and-route-info

The Route component send it down to the components it renders so you can easily access it using `export let currentRoute;` in those components.

If Breadcurmbs.svelte is a child of a <Route /> component just do `export let currentRoute;` and you will have all the information of the route. If it's not a child you need to send it down from the parent component.

As currentRoute is an array of the different parts of the path name it is very easy generating breadcrumbs based on that info.

Anyway your comment makes me think why the store is not exposed.  I need to think about it, maybe the right thing is to expose the store.

**Comment by acaxon** [comment]
Hi, Jorge. Thank you for the quick answer, but it's not so clear to me.

> You have all the information about the active route in a property called currentRoute.
> 
> https://github.com/jorgegorka/svelte-router#layouts-and-route-info
> 
> The Route component send it down to the components it renders so you can easily access it using export let currentRoute; in those components.

Yes, my first idea was to create a Store with breadcrumbs so the Sevelt's reactive engine will update Breadcrumbs component automatically, but I'd have to set this Store in "onMount" hook for every component of every route. Or am I missing something?
