### ISSUE TITLE
Named params with nested routes not rendered correctly

### ISSUE THREAD

**Issue by jorgegorka** [jorgegorka/svelte-router#4]
If we have two routes like:

/employee/show/:id
/employee/show/:id/list

when the url is:

/employee/show/batman

The rendered route is list when it should be show

**Comment by Baudin999** [comment]
I seem to be running into the same issue:

I am trying to get the named params to work, I have a set of routes:

```
const routes = [
  { name: "/project/:projectName/details", component: ProjectDetails }
];
```

I am trying to keep the routs as simple as possible. What I would expect is that the URL:

```
http://localhost:5000/project/Something/details
```

What I get as the `currentRoute` is:

```
{
    "name": "/project/details",
    "component": "",
    "queryParams": {},
    "namedParams": {
        "projectName": "details"
    },
    "path": "/project/Something/details"
}
```

What I would expect is:

```
{
    "name": "/project/:projectName/details",
    "component": "",
    "queryParams": {},
    "namedParams": {
        "projectName": "Something"
    },
    "path": "/project/Something/details"
}
```

Am I doing something wrong? If needed I can try and create an example to reproduce.
