### ISSUE TITLE
routeIsActive when routerCurrent is undefinded

### ISSUE THREAD

**Issue by bovatitar** [jorgegorka/svelte-router#43]
I got error in a newly created project.
Error is:
```
Uncaught TypeError: Cannot read property 'isActive' of undefined
    at routeIsActive (spa_router.js:107)
    at Object.c (navigate.svelte:25)
    at q (index.mjs:1306)
    at Object.c (App.svelte:37)
    at Object.c (App.svelte:35)
    at F (index.mjs:1395)
    at new target (main.js:3)
    at main.js:3
    at main.js:6
```

My component:
```javascript
<script>
	import {Router, Navigate } from 'svelte-router-spa'
	import Com1 from "./Com1.svelte";
	import Com2 from "./Com2.svelte";

	let menu = [
		{
			"name": "Route1",
			"to": "/",
		},
		{
			"name": "Route2",
			"to": "/route2",
		}
	]

	const routes = [
		{
			name: '/',
			component: Com1,
		}, {
			name: 'route2',
			component: Com2,
		}
	]

</script>
<main>
	<h1>Router error</h1>
	{#each menu as menuItem}
		<li>
			<Navigate to="{menuItem.to}">{menuItem.name}</Navigate>
		</li>
	{/each}
	<Router {routes}/>
</main>
```

Version info:
"svelte-router-spa": "^5.4.3",
"svelte": "^3.19.2"

**Comment by bovatitar** [comment]
Editing this function in spa_router.js:107 works for me.
```javascript
function routeIsActive(queryPath, includePath = false) {
  return typeof routerCurrent !== "undefined" ? routerCurrent.isActive(queryPath, includePath) : false
}
```

**Comment by jorgegorka** [comment]
You are trying to use the router before it has been initialised and that's what generates the error. 

In your App file just initialise the router and then add all the html markup in a template with a `Route` component.  
In your example the best approach would be to add a layout like this:

```:javascript
const routes = [
		{
			name: '/',
			component: Com1,
                        layout: MainLayout
		}, {
			name: 'route2',
			component: Com2,
                        layout: MainLayout
		}
	]
```

And MainLayout.svelte would be something like this:

```
<script>
  import { Route } from 'svelte-router-spa'
  import TopHeader from './top_header.svelte'
  export let currentRoute
  const params = {}
</script>

<main>
	<h1>Router error</h1>
	{#each menu as menuItem}
		<li>
			<Navigate to="{menuItem.to}">{menuItem.name}</Navigate>
		</li>
	{/each}
	<Route {currentRoute}  {params} />
</main>
```

Hope this helps.  There is another example here: https://github.com/jorgegorka/svelte-router#usage for an example of use.

And you can check a full app here: https://github.com/jorgegorka/demanda/tree/master/frontend/src

**Comment by bovatitar** [comment]
Another question is about why this code worked properly in version 5.3.3 and my project before update. But anyway, thank you

**Comment by jorgegorka** [comment]
@bovatitar _routeIsActive_ was doing an extra call to the router in case it was undefined.  But that had an impact in other areas like the browser history.  Now it's more accurate.
