### ISSUE TITLE
Question how router loading layout and component

### ISSUE THREAD

**Issue by jadeja-rajdeep** [jorgegorka/svelte-router#47]
hello i have one question before going to deep dive into your router library

from your given example 

const routes = [
  {
    name: '/',
    component: PublicLayout
  },
  { name: 'login', component: Login, layout: PublicLayout },
  {
    name: 'admin',
    component: AdminLayout,
    onlyIf: { guard: userIsAdmin, redirect: '/login' },
    nestedRoutes: [
      { name: 'index', component: AdminIndex },
      {
        name: 'employees',
        component: '',
        nestedRoutes: [
          { name: 'index', component: EmployeesIndex },
          { name: 'show/:id', component: EmployeesShow }
        ]
      }
    ]
  }
]

if i first visit '/' home page of website
then i visit the '/login' 

is this router again load the 'PublicLayout' and then try to add the component inside it which is 'Login'

simply i want know that is this router is re-rendering the whole thing layout + component?

thanks

**Comment by jorgegorka** [comment]
Hello @jadeja-rajdeep 

The render process is controlled by Svelte. It's Svelte the one that decides what should be updated depending on what's changed from one request to another.  

So when you go from one route to another all the files are evaluated layout + component but what will be re-render depends on Svelte and the changes made to those files.

In the example you mention:  When you first visit '/' home as nothing has been rendered previously the layout will be rendered but when you visit '/login' only what's changed will be re-rendered, or nothing if the layout does not change from one route to the other.

Svelte does a very good job optimising what's changed and which parts of the page should be refreshed and which can stay as they are.

**Comment by jadeja-rajdeep** [comment]
@jorgegorka thank you very much sir clearing my doubt about this.

i am just trying to learn the svelte and find out your routing library

thanks
