### ISSUE TITLE
Loading required data for a route

### ISSUE THREAD

**Issue by robfletcher** [jorgegorka/svelte-router#49]
Is there any support for a data loading callback for a route? For example if I have a `/users/:id` route, I'd like to fetch the data for the user (from XHR or indexeddb, for example) before dispatching to the route, redirecting to 404 if the `id` is invalid.

Is the correct way to do that via `onlyIf`, or would it maybe warrant a separate thing?

**Comment by jorgegorka** [comment]
Hi @robfletcher Thank you for your comment.

Getting data from the user and decide what to do is actually business logic and I don't think the router should handle any of that.  

What I do is having those checks in the templates that I want to protect (only logged in users, only admins, only users... etc.).  That way all the business logic is inside your app and you decide what to do when a condition fails (redirect to another url, show an error page... you choose)

If you want to see a couple of examples of this approach please check:

Here the backend is a Ruby on Rails application that sends a JWT to the client.

https://github.com/jorgegorka/demanda/blob/master/frontend/src/lib/session/index.js

And this example use Google's Firebase

https://github.com/jorgegorka/svelte-firebase/blob/master/src/middleware/users/auth.js
