### ISSUE TITLE
can't forward page

### ISSUE THREAD

**Issue by kapilpipaliya** [jorgegorka/svelte-router#51]
when i navigate page to back, i cant forward. forward history is cleaned.
https://github.com/kapilpipaliya/svelte-router-bug

**Comment by kapilpipaliya** [comment]
I can only navigate back only one page, because when i press back button on chrome, the library is pushing new history state.

**Comment by jorgegorka** [comment]
Thanks for reporting this @kapilpipaliya

**Comment by morelazers** [comment]
Would really like to create a persistent "back" button in my app when not on the default route, and I have a few nested routes - currently have the same issue where back only works once.

**Comment by jorgegorka** [comment]
I've deployed version 5.8.3 that fixes the problem with the back button.  It should work fine now.
