### ISSUE TITLE
Is the scroll position resetted on every path change?

### ISSUE THREAD

**Issue by PierBover** [jorgegorka/svelte-router#54]
I don't see any mention of this in the docs.

Sometimes it makes sense to reset scroll to the top of the page when navigating to a route, but sometimes it doesn't (eg: switching tabs in a UI).

**Comment by artecoop** [comment]
@PierBover I support your issue.
I think that a scrolling behavior is required for a router. Although UI changes must be handled by the UI itself, an action to scroll up is critical, either like a basic boolean (scroll up to 0,0 or not) or via callback (as angular does, for example)

**Comment by jorgegorka** [comment]
Hello @PierBover @artecoop I'm not sure about that.

I don't think the router should be too smart.  Scrolling is something that impacts accessibility and user behavior. 

It should be the developers in their apps those who decide if scroll is needed and how much of it.

**Comment by PierBover** [comment]
My point was that the router needs to help the developer implement the desired behavior, not that it should have a default behavior.

**Comment by jorgegorka** [comment]
So what do you suggest @PierBover ?

Currently scroll is supported like this:  https://developer.mozilla.org/en-US/docs/Web/API/History/scrollRestoration

Do you think the router should let the developer configure that value globally for the whole app, per each route ?

**Comment by PierBover** [comment]
The thing with scroll restoration is that it's always the same behavior. This is desirable when going to different pages, as in from `/home` to `/about`. But this is not desirable when you have a tab submenu in a nested route for example in which the best UX is to not reset the scroll.

As you say, one option is to configure it on the each route. But what happens when you have nested routes? Maybe there could be a conflict between a parent and a child route.

I think I'd prefer to implement a global setting in the router for the default behavior, and then a way to override that. For example something like `<a href="/about" no-scroll>About</a>` and then something like `Navigate.to('/about', {scroll: false})`.

In Sapper this is accomplished via: `<a href="/hello" sapper-noscroll>edit</a>`. AFAIK `goto()`doesn't support scroll config.

**Comment by artecoop** [comment]
I'd rather have a callback on every route event, maybe with the route as parameter, so I can handle it as I want, with the granularity I need
