### ISSUE TITLE
is there anything comparable to beforeRouteEnter (vue)?

### ISSUE THREAD

**Issue by dustypaws** [jorgegorka/svelte-router#60]
I want to check if the users JWT token is still valid or if I need to refresh the session before a given component is rendered. A good way to accomplish that would be a lifecycle hook on route change. Is there anything like that or am I missing something?

Thanks in advance! :)

**Comment by dustypaws** [comment]
I guess 
```
(function() {
  // ...do something here...
}());
```

in `routes.js` could work....it's a bit messy tho.

**Comment by jorgegorka** [comment]
Hello @dustypaws 

I'm not sure a hook is the best place to trigger that behaviour.

This is an example of how I do it.

https://github.com/jorgegorka/demanda/blob/master/frontend/src/views/protected/admin/layout/index.svelte#L20-L38
_(Probably those lines can be extracted out to a file but I think it serves as an example.)_

The problem with hooks is that they are only triggered when a route changes. With the approach in that example currentUser is a store and is reactive so even if the user doesn't navigate anywhere that logic will be triggered when something changes.

**Comment by dustypaws** [comment]
Thanks for the answer! 
Having a look later and closing this for now. 👍 :)
