### ISSUE TITLE
[Feature request] - Add transition

### ISSUE THREAD

**Issue by BenoitPingris** [jorgegorka/svelte-router#62]
Is it possible to add a feature to use svelte's transition on the <Route /> component ?
Something like this:

```html
<script>
import { fade } from 'svelte/transition';
import { Route } from 'svelte-router-spa';

export let currentRoute;
export let params = {};

</script>

<Route transition:fade {currentRoute} {params} />
```

I'm not a svelte expert so maybe there's a way to use transition on the <Route /> component, but I don't know it !
 

Anyway, thanks for this package, it works really well (except for this feature that I'd love to have) !

**Comment by gustavopch** [comment]
@jorgegorka Why was this issue closed? Are route transitions considered out of the scope of this package? I'm comparing this package to https://github.com/roxiness/routify and they mention route transitions as a feature there.

**Comment by jorgegorka** [comment]
Hey @gustavopch 

I try to keep the router as less opinionated as possible. Transitions have an impact on UX and depending on your application they may not suit well. So I would keep the router focused on doing just the route part.  It's very easy to implement your transitions, if you want them, inside a template.

Cheers,
