### ISSUE TITLE
Don't redirect to a /404 route if the route could not be found

### ISSUE THREAD

**Issue by mjarkk** [jorgegorka/svelte-router#7]
It's a bit annoying and unusual for a router to redirect to a /404 route.  
I don't know of any website's that redirect a user to a /404 page when the route is not found.  

Beside that it only replaces the last part of the URL what seems wired to me, if the user gets redirect to a 404 page why not replace the full path.  
```
/some/not/exsiting/url > /some/not/exsiting/404
```

**Comment by jorgegorka** [comment]
Hello @mjarkk Yes, that's something I've got on the todo list for a while.

404 pages are not handled as they should. I'll try and change it soon.

**Comment by jorgegorka** [comment]
@mjarkk There is a new version that redirects to a /404.html page.

I've been checking what the standard procedure for SPAs is and it looks like that is the best approach and supported by all mayor hosting platforms.

There is no need to pass a notFound component when initialising SpaRouter.  I've updated the docs.

**Comment by mylastore** [comment]
I know this is closed but the current 404.html is not working for me it just goes to a blank page, I used this [spa-router ](https://github.com/ItalyPaleAle/svelte-spa-router#readme) and there is a catchall router to handle the not found route 
```
import NotFound from './views/NotFound.svelte'

const routes = {

    // Catch-all
    // This is optional, but if present it must be the last
    '*': NotFound,
}
```
