### ISSUE TITLE
No way to open in new window

### ISSUE THREAD

**Issue by stripeyhorse** [jorgegorka/svelte-router#74]
I have a route that i would like to open in a new window (its for creating a PDF)

i have the following in routes
{ name: 'PDF/:userid/:orderid/', component: PDF, layout: PDFLayout}

and the link to open the new window
 target="_blank" href="/PDF/{user.uid}/{order.id}

but i cant for the life of me get it too open a new window.

**Comment by jorgegorka** [comment]
I'll release a fix ASAP.

Thanks for reporting this @stripeyhorse

**Comment by stripeyhorse** [comment]
thanks @jorgegorka such a great router that is very easy to use.

**Comment by jorgegorka** [comment]
Hi @stripeyhorse I've released version 5.7.2 that should solve the problem.

Enjoy it!
