### ISSUE TITLE
Uncaught TypeError: src.Router is not a constructor

### ISSUE THREAD

**Issue by morecoffee11** [jorgegorka/svelte-router#79]
After installing version 15.0.0 of "@rollup/plugin-commonjs" apps don't build anymore... 
With version 14.0.0 its ok.
Thanks for your work.

**Comment by vsviridov** [comment]
Experiencing same issue... Downgrading to 14 helps.

**Comment by cliveportman** [comment]
Same error when using 16.0.0

**Comment by ffvpor** [comment]
@morecoffee11 @vsviridov @cliveportman
In my case, after updating `rollup.config.js`file (more details in https://github.com/jorgegorka/svelte-router/issues/91#issuecomment-739134344), this error goes away even with the latest version of `@rollup/plugin-commonjs`
I hope it helps you
