### ISSUE TITLE
Better handling of routes with no component

### ISSUE THREAD

**Issue by mjarkk** [jorgegorka/svelte-router#8]
When i use this route config:
```js
{
  name: '/test/route',
  nestedRoutes: [
    {
      name: 'something',
      component: Dashboard,
    }
  ],
}
```
then go to `/test/route` i expect to see my defined 404 page but in staid i get an empty page.

**Comment by jorgegorka** [comment]
I've been thinking about this issue.  As per design if you want to render a nested route you need a parent component/layout that renders a <Route />. It's the only way nested components can access route information. 

The example you mention above shows a wrong configuration so displaying a 404 page is misleading.
