### ISSUE TITLE
How to handle internal HTML links?

### ISSUE THREAD

**Issue by agrawal-rohit** [jorgegorka/svelte-router#80]
I have a landing page with multiple regions I want to navigate to using links. Navigating using id's does not work when I'm using this library. How do I handle the included hash in the url through internal links? 

**For example:**
My landing page is at the URL '/', and after clicking the internal link the URL should be '/#features'. When I click the button, nothing happens

**Comment by jorgegorka** [comment]
Hi @agrawal-rohit 

There was an issue but was solved in version 5.7.1 

Do you have the latest version?
