### ISSUE TITLE
Layout does not update on route change

### ISSUE THREAD

**Issue by cope** [jorgegorka/svelte-router#81]
This is my App.svelte:
```
<script>
	import {Router} from 'svelte-router-spa';
	import {routes} from 'routes';
</script>
<Router {routes}/>
```

This is my routes.js
```
import Layout from './Layout.svelte';
import About from "./About.svelte";
import Lorems from "./Lorems.svelte";

const routes = [
	{name: '/', layout: Layout, component: Lorems},
	{name: 'about', layout: Layout, component: About}
];
export {routes};
```

This is my Layout.svelte:
```
<script>
	import {Route} from 'svelte-router-spa';
	import Menu from './Menu.svelte';

	export let currentRoute;
	const params = {};
</script>

<Menu/>
<br />
<Route {currentRoute} {params}/>
```

Now, in the Menu.svelte I want to show only one nav link, depending which page I am in.
If I am in / I want to show <Navigate to="/about">About</Navigate>,
and if I am in /about I want to show <Navigate to="/">Mahahaklice</Navigate>
but I cannot get it to work, because the layout does not get informed when the route changes.

How can I inform Menu that the route has changed?

**Comment by jorgegorka** [comment]
Hey @cope 

Here is a working example of updating the menu with the selected option

https://github.com/jorgegorka/demanda/blob/master/frontend/src/views/protected/admin/layout/main_menu/item.svelte

**Comment by cope** [comment]
It does not work. The currentRoute does not change its value in the Layout when the path changes.

It prints it only on the first load, and then during navigation it does not change.

It is like Layout is rendered only once and that's it, even though the Route part does change, but not anything around it in the Layout.
