### ISSUE TITLE
'/' for parent routes not work when defining nested routes.

### ISSUE THREAD

**Issue by KamyarLajani** [jorgegorka/svelte-router#86]
Example: i have two parent routes '/' for main page and 'admin'. the admin one has nested routes, i want 'admin/' or just 'admin' itself render the AdminIndex component without adding a nested route called 'index' or any value.
when i reach any other nested routes the library always renders the AdminIndex component and the nested components will not render. i only have to add a nested route called 'index' for example and rendering AdminIndex with it and deleting AdminIndex from the top.

```
const routes = [
 {name: '/', component: Index}, 
  {
    name: 'admin',
    component: AdminIndex,
    nestedRoutes: [
        { name: 'login', component: AdminLogin },
        { name: 'login/forgetpassword', component: ForgetPassword },
        { name: 'login/changepassword/:email', component: ChangePassword },
        {name: 'about/:id', component: About, onlyIf: { guard: isAuth, redirect: '/login' }},
  ]
  },
]
```
I only have to use another name instead of '/' in nested route for making index route for the admin.

```
const routes = [
  {name: '/', component: Index}, 
  {
    name: 'admin',
    nestedRoutes: [
        { name: 'index', component: AdminIndex },
        { name: 'login', component: AdminLogin },
        { name: 'login/forgetpassword', component: ForgetPassword },
        { name: 'login/changepassword/:email', component: ChangePassword },
        {name: 'about/:id', component: About, onlyIf: { guard: isAuth, redirect: '/login' }},
  ]
  },
]
```

**Comment by jorgegorka** [comment]
Hi @KamyarLajani 

You can't have two routes with the same name and at the same level as they will overlap. 

You can find a good example of routes here:  both public and private with many nested levels.

https://github.com/jorgegorka/demanda/tree/master/frontend/src/lib/routes
