### ISSUE TITLE
Route parameters matching incorrectly and redirecting to root?

### ISSUE THREAD

**Issue by nickyhajal** [jorgegorka/svelte-router#88]
Here's a REPL that doesn't seem to be working on the website, but illustrates the situation if you run locally.

https://svelte.dev/repl/13608c5e9280428f81c0b8dc9bc2b97c?version=3.29.4

If you go to `/a`, it correctly outputs 2

If you go to `/a/b`, I would expect it to output 3 but it outputs 4 and redirects to `/a`

If you go to `/a/b/c`, it outputs 4 and redirects to `/a/c`

Why is this not behaving as expected? Am I doing something wrong?

**Comment by jorgegorka** [comment]
Hello @nickyhajal 

Here is the right configuration :

```
const routes = [
    {
      name: '/',
      component: 'Comp1',
    },
    { 
      name: '/a/:id', component: 'Comp2', 
      nestedRoutes: [{ name: 'b', component: 'Comp4' }] 
    },
  ]
```

The reason behind it is that named params `id` in this example, are optional so /a/123 and /a are rendered by the same component `Comp2` in the first case the param id will be 123 and in the second it'll be empty.

Then you can have nested routes but you need to use the nested route property to indicate it.

**Comment by nickyhajal** [comment]
Thanks for the quick response @jorgegorka, that makes sense!
