### ISSUE TITLE
<Component> was created with unknown prop 'params'

### ISSUE THREAD

**Issue by standup75** [jorgegorka/svelte-router#9]
Thank you for the router, it looks very good to me so far.

I just have a question, when I add `export let currentRoute` in my component (let's call it "Component"...) I get this warning `<Component> was created with unknown prop 'params'`

Any idea why that is?

**Comment by standup75** [comment]
Nevermind, just needed to add `export let params` or ignore the warning.

**Comment by jorgegorka** [comment]
Hi @standup75 :

params let you send custom information to the route and their children components.  

Yes, the right solution is to define it as you did.

**Comment by jhon-andrew** [comment]
I got into this issue as well. It got me confused because according to your README.md file, it is defined as `const params = {}` wherein it should really be defined the same as how @standup75 did.

Maybe you could see and update that for others.

**Comment by fuchunhui** [comment]
It's work, a strange way even if I didn't use them.
`export let params;`
`export let currentRoute;`
