### ISSUE TITLE
Use with Svite gives does not provide an export named 'Router'

### ISSUE THREAD

**Issue by quantuminformation** [jorgegorka/svelte-router#90]
I'm trying to use this router but I get `Uncaught SyntaxError: The requested module '/@modules/svelte-router-spa.js' does not provide an export named 'Router'`
 for this code
`    import { Router } from 'svelte-router-spa'`

**Comment by SvenSchoene** [comment]
Just stumbled upon the same issue.
Here's what has helped me:

Create a new file `src/decs.d.ts` with the following content:

```ts
declare module "svelte-router-spa" {
  var Router: any;
  export default Router;
}
```

This shouldn't be necessary, but in `./tsconfig.json` I explicitly add this file to `included`, which looks like this now for me:

```ts
{
  ...
  "include": ["src/**/*", "src/decs.d.ts"],
   ...
}
```

And my `App.svelte` looks like this:

```svelte
<script lang="ts">
  import Router from "svelte-router-spa";
  import { routes } from "./routes";
</script>

<style>
</style>

<Router.Router {routes} />
```

Works fine for me. Hope it will for you too!

**Comment by quantuminformation** [comment]
wow thx, but I'm not even using ts.

**Comment by cotlod** [comment]
Just

`<script lang="ts">
  import { Router } from 'svelte-router-spa'
  import { routes } from './routes'
</script>

<style>
</style>

<Router.default {routes} />`

works aswell

**Comment by jorgegorka** [comment]
Please upgrade to version 6 that supports esm, thank you.
