### ISSUE TITLE
Uncaught TypeError: src.Router is not a constructor

### ISSUE THREAD

**Issue by aacassandra** [jorgegorka/svelte-router#91]
When include this on App.svelte
import { Router } from "svelte-router-spa";
im getting error
Uncaught TypeError: src.Router is not a constructor

i'm new on svelte, somebody helpme?

**Comment by ffvpor** [comment]
Perhaps, answer to this issue #79 can helps you

**Comment by ffvpor** [comment]
I also ran into this problem and after a lot of research... adding option below in `rollup.config.js` file seems resolve error

```js
...
  commonjs({
    "requireReturnsDefault": true
  }),
...
```
My `package.json`

```json
├── @rollup/plugin-commonjs@17.0.0
├── @rollup/plugin-node-resolve@11.0.0
├── @rollup/plugin-typescript@8.0.0
├── @tsconfig/svelte@1.0.10
├── autoprefixer@10.0.4
├── postcss@8.1.14
├── rollup@2.34.1
├── rollup-plugin-css-only@3.0.0
├── rollup-plugin-livereload@2.0.0
├── rollup-plugin-serve@1.1.0
├── rollup-plugin-svelte@7.0.0
├── rollup-plugin-terser@7.0.2
├── sirv-cli@1.0.8
├── svelte@3.31.0
├── svelte-check@1.1.18
├── svelte-preprocess@4.6.1
├── svelte-router-spa@5.8.1
├── tailwindcss@2.0.1
├── tslib@2.0.3
└── typescript@4.1.2
```

More details [here](https://github.com/rollup/plugins/tree/master/packages/commonjs#requirereturnsdefault)

**Comment by aacassandra** [comment]
wow, thank you. yesterday I was also worried about this. maybe some time in the future i will try again @ffvpor

**Comment by sallaben** [comment]
@ffvpor 

Value of `true` did not work for me. However value of `'auto'` did.

```
    commonjs({
      requireReturnsDefault: 'auto',
    }),

**Comment by aacassandra** [comment]
> ```json
> @rollup/plugin-node-resolve
> ```

unfortunately i don't use TS and not work with js.

is there an example repo for this?
