### ISSUE TITLE
Uncaught TypeError: src.Router is not a constructor

### ISSUE THREAD

**Issue by jklemm** [jorgegorka/svelte-router#97]
Hi!

I'm just trying to make it work with a simple code, but I receive this error when running on Windows 10 x64 - Chrome 87.0.4280.88 64 bits.

![image](https://user-images.githubusercontent.com/5324645/103040609-b1f21800-4552-11eb-8084-02f14d73eb2f.png)

## My Code:

main.svelte
```
import App from './App.svelte';

const app = new App({ target: document.body });

export default app;
```

App.svelte
```
<script>
  import { Router } from 'svelte-router-spa'
  import { routes } from './routes'
</script>

<Router {routes} />
```

routes.js
```
import Dashboard from './views/dashboard.svelte'

const routes = [
  { name: '/', component: Dashboard }
]

export { routes }
```

views/dashboard.svelte
```
<div>
    <h1>Dashboard</h1>
</div>
```

I run using `rollup -c -w` and `sirv public -s`, both give me same error.

I'm lost.  Can you help me?

Thanks!

**Comment by ffvpor** [comment]
Hello
i hope that answers to this issue #91 can helps you

**Comment by jklemm** [comment]
Hi @ffvpor,

Yes, adding `commonjs({ requireReturnsDefault: 'auto', }),` to `rollup.config.js` solve the problem.

Maybe, this info needs to be on installation or tutorial, to avoid this behaviour to new devs using svelte-router.

**Comment by robertfausk** [comment]
I got same error with webpack bundling.
I could solve it by using `<Route.default` and `<Router.default` from https://github.com/jorgegorka/svelte-router/issues/90#issuecomment-753722214 which seems quite strange to me but at least it's working for me.

**Comment by matiaspando** [comment]
Same problem here!  Solved adding commonjs({ requireReturnsDefault: 'auto', }), to rollup.config.js

**Comment by jorgegorka** [comment]
Please upgrade to version 6 that support esm packages.
